services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.output:/app/.output
    ports:
      - "${FRONTEND_PORT}:80"
    expose:
      - "3000"
  build:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx
