services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./:/app
      - ./node_modules/:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - docker/.env
    command: npm run dev
    stdin_open: true
    tty: true
